---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600

    - name: Install git.
      apt:
        name: git
        state: present

  roles:
    - role: djonasson.xdg_bds
