---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

    - name: Install git.
      ansible.builtin.apt:
        name: git
        state: present

  roles:
    - role: djonasson.xdg_bds
